apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtr-app-be
spec:
  replicas: 3
  minReadySeconds: 15
  selector:
    matchLabels:
      app: twtr-app-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: twtr-app-be
    spec:
      containers:
        - image: saikiranreddykonda/backend
          imagePullPolicy: Always
          name: twtr-app-be
          ports:
            - containerPort: 5000
